spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/student
    username: postgres
    password: postgres
logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE
          
